"""央行权威金融术语表（EN → ZH），翻译时强制统一译名。

数据来源：中国人民银行/美联储/Fed/BIS 等官方中文表述习惯，以及简报高频词汇。
用户可通过编辑本文件增删术语。
"""

MULTI_WORD = {
    # ---- 货币政策工具与操作 ----
    "open market operations": "公开市场操作",
    "open market operation": "公开市场操作",
    "policy rate": "政策利率",
    "policy rates": "政策利率",
    "policy interest rate": "政策利率",
    "repo rate": "回购利率",
    "reverse repo": "逆回购",
    "overnight repo": "隔夜回购",
    "discount rate": "贴现率",
    "reserve requirement ratio": "存款准备金率",
    "reserve requirements": "准备金要求",
    "required reserves": "法定准备金",
    "excess reserves": "超额准备金",
    "reserve buffer": "准备金缓冲",
    "excess liquidity": "超额流动性",
    "liquidity buffer": "流动性缓冲",
    "standing facilities": "常备借贷便利",
    "lender of last resort": "最后贷款人",
    "quantitative easing": "量化宽松",
    "quantitative tightening": "量化紧缩",
    "balance sheet policy": "资产负债表政策",
    "balance sheet": "资产负债表",
    "forward guidance": "前瞻性指引",
    "interest rate guidance": "利率指引",
    "rate cut": "降息",
    "rate hikes": "加息",
    "rate increase": "加息",
    "rate reductions": "降息",
    "expectations channel": "预期渠道",
    "signaling channel": "信号渠道",
    "lending operations": "借贷便利操作",
    "term deposit facility": "定期存款便利",
    "auction": "招标/拍卖",
    "bond purchases": "债券购买",
    "asset purchases": "资产购买",
    "asset purchase programme": "资产购买计划",
    "unconventional monetary policy": "非常规货币政策",
    "conventional monetary policy": "常规货币政策",
    "monetary easing": "货币宽松",
    "monetary tightening": "货币紧缩",
    "easy monetary policy": "宽松货币政策",
    "tight monetary policy": "紧缩货币政策",
    "withdrawal of accommodation": "政策宽松退出",
    "monetary accommodation": "货币政策宽松",
    "policy normalization": "政策正常化",
    "policy stance": "政策立场",
    "calibration of policy": "政策校准",
    "autonomous factors": "自主性因素",
    "ample reserves": "充足准备金",
    "scarce reserves": "稀缺准备金",
    "corridor system": "利率走廊制度",
    "floor system": "利率地板制度",
    "ceiling": "上限",
    "zero lower bound": "零利率下限",
    "effective lower bound": "有效利率下限",

    # ---- 利率与信贷传导 ----
    "transmission mechanism": "传导机制",
    "monetary transmission": "货币政策传导",
    "interest rate transmission": "利率传导",
    "credit channel": "信贷渠道",
    "bank lending channel": "银行信贷渠道",
    "balance sheet channel": "资产负债表渠道",
    "risk-taking channel": "风险承担渠道",
    "pass-through": "传导",
    "pass-through of": "…对…的传导",
    "lending rates": "贷款利率",
    "deposit rates": "存款利率",
    "mortgage rates": "抵押贷款利率",
    "loan rates": "贷款利率",
    "wage growth": "工资增长",
    "credit conditions": "信贷条件",
    "financing conditions": "融资条件",
    "financial conditions": "金融条件",
    "monetary conditions": "货币条件",
    "headline inflation": "总体通胀",
    "core inflation": "核心通胀",
    "underlying inflation": "潜在通胀",
    "inflation expectations": "通胀预期",
    "disinflation": "通胀回落",
    "deflationary pressures": "通缩压力",
    "price stability": "物价稳定",
    "cost-push inflation": "成本推动型通胀",
    "demand-pull inflation": "需求拉动型通胀",
    "wage-price spiral": "工资-价格螺旋",
    "terms of trade": "贸易条件",
    "purchasing power": "购买力",
    "real interest rate": "实际利率",
    "real rates": "实际利率",
    "nominal rate": "名义利率",
    "neutral rate": "中性利率",
    "natural rate": "自然利率",
    "r-star": "均衡实际利率",
    "Taylor rule": "泰勒规则",
    "Phillips curve": "菲利普斯曲线",
    "output gap": "产出缺口",
    "potential output": "潜在产出",
    "unemployment rate": "失业率",
    "labor market": "劳动力市场",
    "labour market": "劳动力市场",
    "tight labor market": "紧张的劳动力市场",
    "fiscal policy": "财政政策",
    "fiscal stimulus": "财政刺激",
    "fiscal space": "财政空间",
    "government debt": "政府债务",
    "sovereign debt": "主权债务",
    "public debt": "公共债务",
    "debt sustainability": "债务可持续性",
    "fiscal-monetary coordination": "财政货币政策协调",

    # ---- 金融稳定与风险 ----
    "financial stability": "金融稳定",
    "systemic risk": "系统性风险",
    "financial stress": "金融压力",
    "financial vulnerabilities": "金融脆弱性",
    "macroprudential policy": "宏观审慎政策",
    "macroprudential tools": "宏观审慎工具",
    "countercyclical capital buffer": "逆周期资本缓冲",
    "capital buffer": "资本缓冲",
    "capital requirements": "资本要求",
    "capital adequacy": "资本充足",
    "liquidity requirements": "流动性要求",
    "liquidity coverage ratio": "流动性覆盖率",
    "leverage ratio": "杠杆率",
    "stress test": "压力测试",
    "stress testing": "压力测试",
    "bank run": "银行挤兑",
    "deposit insurance": "存款保险",
    "shadow banking": "影子银行",
    "non-bank financial institutions": "非银行金融机构",
    "non-bank financial intermediation": "非银行金融中介",
    "asset-liability management": "资产负债管理",
    "duration risk": "久期风险",
    "credit risk": "信用风险",
    "market risk": "市场风险",
    "liquidity risk": "流动性风险",
    "interest rate risk": "利率风险",
    "tail risk": "尾部风险",
    "spillover": "溢出效应",
    "spillovers": "溢出效应",
    "contagion": "传染效应",
    "fire sales": "抛售/贱卖",
    "asset bubble": "资产泡沫",
    "housing market": "住房市场",
    "commercial real estate": "商业地产",
    "default rate": "违约率",
    "non-performing loans": "不良贷款",
    "loan loss provisions": "贷款损失拨备",
    "fair value": "公允价值",

    # ---- 汇率与开放经济 ----
    "exchange rate": "汇率",
    "exchange rates": "汇率",
    "foreign exchange": "外汇",
    "foreign exchange reserves": "外汇储备",
    "floating exchange rate": "浮动汇率制度",
    "fixed exchange rate": "固定汇率制度",
    "exchange rate pass-through": "汇率传导",
    "currency depreciation": "本币贬值",
    "currency appreciation": "本币升值",
    "capital flows": "资本流动",
    "capital inflows": "资本流入",
    "capital outflows": "资本流出",
    "current account": "经常账户",
    "trade balance": "贸易余额",
    "safe-haven": "避险",
    "safe haven": "避险",
    "dollar funding": "美元融资",
    "foreign currency liquidity": "外币流动性",
    "global financial cycle": "全球金融周期",
    "trilemma": "不可能三角",
    "international reserves": "国际储备",
    "emerging market economies": "新兴市场经济体",
    "advanced economies": "发达经济体",
    "currency union": "货币联盟",
    "euro area": "欧元区",

    # ---- 治理、数据与结构 ----
    "central bank independence": "中央银行独立性",
    "inflation targeting": "通胀目标制",
    "policy framework": "政策框架",
    "operating framework": "货币政策操作框架",
    "monetary policy framework": "货币政策框架",
    "policy decision": "政策决定",
    "policy meeting": "政策会议",
    "deliberation": "审议",
    "panel": "专家组",
    "working paper": "工作论文",
    "discussion paper": "讨论稿",
    "staff report": "工作人员报告",
    "vintage data": "时点数据/特定版本数据",
    "real-time data": "实时数据",
    "sectoral": "部门层面的",
    "heterogeneous": "异质性的",
    "heterogeneity": "异质性",
    "frictions": "摩擦",
    "nominal rigidities": "名义刚性",
    "price stickiness": "价格粘性",
    "menu costs": "菜单成本",
    "search and matching": "搜寻与匹配",
    "rich households": "高收入家庭",
    "low-income households": "低收入家庭",
    "marginal propensity to consume": "边际消费倾向",
    "consumption smoothing": "消费平滑",
    "savings rate": "储蓄率",
    "household debt": "家庭债务",
    "corporate leverage": "企业杠杆",
    "productivity growth": "生产率增长",
    "total factor productivity": "全要素生产率",
    "supply-side": "供给侧",
    "demand-side": "需求侧",

    # ---- 数字金融与金融科技 ----
    "central bank digital currency": "中央银行数字货币",
    "digital currency": "数字货币",
    "distributed ledger technology": "分布式账本技术",
    "stablecoin": "稳定币",
    "stablecoins": "稳定币",
    "tokenized deposits": "代币化存款",
    "tokenization": "代币化",
    "wholesale CBDC": "批发型央行数字货币",
    "retail CBDC": "零售型央行数字货币",
    "programmability": "可编程性",
    "payment system": "支付系统",
    "payment systems": "支付系统",
    "real-time gross settlement": "实时全额结算",
    "cross-border payments": "跨境支付",
    "settlement risk": "结算风险",
    "financial inclusion": "普惠金融",
    "digital finance": "数字金融",
    "buy now pay later": "先买后付",
    "credit scoring": "信用评分",
    "data privacy": "数据隐私",
}

# 完全大写/首字母缩写，不做替换（避免误伤公式），统一在中英文均保留
ACRONYMS = {
    "CBDC": "央行数字货币",
    "QE": "量化宽松",
    "QT": "量化紧缩",
    "LSAP": "大规模资产购买",
    "DSGE": "动态随机一般均衡",
    "VAR": "向量自回归",
    "SVAR": "结构向量自回归",
    "NPL": "不良贷款",
    "LCR": "流动性覆盖率",
    "CCyB": "逆周期资本缓冲",
    "FOMC": "联邦公开市场委员会",
    "MPC": "货币政策委员会",
    "ZLB": "零利率下限",
    "ELB": "有效利率下限",
}


def glossary_text() -> str:
    """生成可直接注入 prompt 的术语表文本。"""
    lines = ["术语对照表（翻译时必须遵从，不得使用其他译名）:"]
    for en, zh in sorted(MULTI_WORD.items(), key=lambda x: len(x[0]), reverse=True):
        lines.append(f"- {en} → {zh}")
    for en, zh in sorted(ACRONYMS.items()):
        lines.append(f"- {en} → {zh}")
    return "\n".join(lines)